accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<int:user_id>', views.profile, name='profile'),
]

products/urls.py
from django.urls import path
from . import views

app_name= 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product_creats/', views.product_creats, name='product_creats'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<int:pk>/update', views.product_update, name='product_update'),
    path('<int:pk>/delete', views.product_delete, name='product_delete'),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/", views.comment_delete, name="comment_delete"),
    path('<int:pk>/like/', views.like, name='like'),
]

sparta_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts', include('accounts.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    following = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse

        
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()



class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = {
            'first_name',
            'last_name',
            'email',
         }
        

    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            
            if self.fields.get("password"):
                password_help_text = (
                    "You can change the password " '<a href="{}">here</a>.'
                ).format(f"{reverse('accounts:change_password')}")
                self.fields["password"].help_text = password_help_text

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import CustomUserChangeForm, CustomUserCreationForm
from .models import User

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get('next') or 'products:index'
            return redirect(next_url)
        
    else:
        form=AuthenticationForm()
        
    context = {
        'form':form
    }
    return render(request, 'accounts/login.html', context)

@require_POST    
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('products:index')

@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form=CustomUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            auth_login(request, user)
            return redirect('products:index')
    else:
        form=CustomUserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect("products:index")


@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("products:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form':form}
    return render(request, 'accounts/update.html', context)
    
@login_required
@require_http_methods(["GET", "POST"])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("products:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)

def profile(request, user_id):
     user= get_object_or_404(User, id=user_id)
     return render(request, 'accounts/profile.html', {'profile_user':user})

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 변경</h1>

<form action="{% url 'accounts:change_password' %}" method= "POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">비밀번호 변경</button>
</form>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<h1>로그인</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="로그인">
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}

<h1>{{ profile_user.username }}님의 프로필 페이지</h1>
<br>

<h3>가입일: {{profile_user.date_joined}}</h3>
<h3>좋아요를 누른 게시글 목록</h3>

<div class="row row-cols-1 row-cols-md-3 g-4">
    


    {% for product in user.like_products.all %}
    
    <div class="col">
    <div class="card" style="width: 20rem;">
        {% if product.image %}
        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.image }}">
        {% endif %}
        <div class="card-body">
          <a href="{% url 'products:product_detail' product.pk %}" class="card-title"><h4>{{ product.title }}</h4></a>
          <p class="card-text">{{ product.content }}</p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">작성자: {{product.author.username}}</li>
          <li class="list-group-item">가격: {{product.price}}원</li>
        </ul>
        <div class="card-bottom">
    
            <div class='card-like'>
                <form action="{% url 'products:like' product.pk %}" method="POST">
                    {% csrf_token %}
                {% if request.user in product.like_users.all %}
                        <button class="btn btn-link text-danger">
                            <i class="bi bi-heart-fill"></i>
                        </button>
                        
                    
                {% else %}
                    <button class="btn btn-link text-danger" >
                        <i class="bi bi-heart"></i>
                    </button>
                {% endif %}
        
                {{ product.like_users.all|length }}
                </form>
            </div>
    
            <div class='card-like'>
                조회수: {{ product.hits }}
            </div>
            
            <div class='card-like'>
                댓글수: {{ product.comment_count }}
            </div>
        </div>
      </div>
    </div>
      {% endfor %}
        
      </div>
    <br>

    <a href="{% url 'products:index' %}">메인으로 돌아가기</a>


{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원 가입</h1>

<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">회원 가입</button>

</form>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}

    <h1>회원정보 수정</h1>
    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">수정하기</button>

    </form>

{% endblock content %}