accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<int:user_id>', views.profile, name='profile'),
]

sparta_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts', include('accounts.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Page Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    {% block head %}{% endblock head %}
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        
      
        <span class="navbar-brand mb-0 h1">
            {% if request.user.is_authenticated %}
            <h4>안녕하세요!, {{ request.user.username }}</h4>
        </span>
        


        <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page">
                <form action="{% url 'accounts:logout'%}" method="POST" >
                    {% csrf_token %}
                    <button type="submit" class="btn btn-light">로그아웃</button>
                </form></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{%url 'accounts:profile' user.pk %}">
                    <button type="submit" class="btn btn-light" >회원 프로필</button>
                </a>

            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <form action="{% url 'accounts:delete'%}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-light">회원 탈퇴</button>
                </form>
            </a>
            </li>
          </ul>

          {% else %}

        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>

        {% endif %}



    </nav>

    <div class="container">
        <div class="child">
        {% block content %}
        {% endblock content %}
        </div>
    </div>
        
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>