accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<int:user_id>', views.profile, name='profile'),
]

products/urls.py
from django.urls import path
from . import views

app_name= 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('product_creats/', views.product_creats, name='product_creats'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('<int:pk>/update', views.product_update, name='product_update'),
    path('<int:pk>/delete', views.product_delete, name='product_delete'),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path("<int:pk>/comments/<int:comment_pk>/delete/", views.comment_delete, name="comment_delete"),
    path('<int:pk>/like/', views.like, name='like'),
]

sparta_market/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('accounts', include('accounts.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.users, name="users"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
]

products/models.py
from django.db import models
from django.conf import settings


class Product(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    image = models.ImageField(upload_to="image/", blank=True)
    price = models.PositiveIntegerField()
    
    author = models.ForeignKey(
		settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="product")
    
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_products"
    )
    
    hits = models.IntegerField(default = 0)
    
    
    def __str__(self):
        return self.title
    


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="comments")
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="comments"
    )
    
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return self.content

products/forms.py
from django import forms
from .models import Product, Comment


class ProductForm(forms.ModelForm):
   class Meta:
       model = Product
       fields = '__all__'
       exclude = ('author', 'like_users', 'hits')
       

class CommentForm(forms.ModelForm):
    class Meta:
       model = Comment
       fields = '__all__'
       exclude = ('product', "user")

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, Comment
from .forms import ProductForm, CommentForm
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from django.db.models import Count

def index(request):
     products = Product.objects.annotate(comment_count=Count('comments')).order_by('-id')
     context = {
         'products': products,
         }
     return render(request, 'products/index.html', context)




def product_creats(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid(): 
            product=form.save(commit=False)
            product.author = request.user
            product.save()
            return redirect('products:product_detail', product.pk)
    else:
        form = ProductForm()
    
    context= {'form':form}
    return render(request, 'products/product_creats.html', context)


@require_POST
def product_delete(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.user.is_authenticated:
        if product.author == request.user:
            product = get_object_or_404(Product, pk=pk)
            product.delete()
    return redirect("products:index")



def product_detail(request,pk):
    product=get_object_or_404(Product, id=pk)
    comment_form=CommentForm()
    comments = product.comments.all().order_by('-pk')
    default_hits = product.hits
    product.hits = default_hits+1
    product.save()
    context = {
        'product':product,
        'comment_form':comment_form,
        'comments' : comments,
    }   
    return render(request, 'products/product_detail.html', context)

@login_required
@require_http_methods(["GET", "POST"])
def product_update(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if product.author == request.user:
        if request.method == "POST":
            form = ProductForm(request.POST, instance=product)
            if form.is_valid():
                product = form.save()
                return redirect("products:product_detail", product.pk)
        else:
            form = ProductForm(instance=product)
    else:
        return redirect("products:index")

    context = {
        "form": form,
        "product": product,
    }
    return render(request, "products/product_update.html", context)

@require_POST
def comment_create(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.product = product
        comment.user = request.user #로그인 했을시만 글쓰기 버튼 보이게
        comment.save()
    return redirect("products:product_detail", product.pk)


@require_POST
def comment_delete(request, pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if comment.user == request.user:
            comment.delete()
    return redirect('products:product_detail' , pk)

@require_POST    
def like(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Product, pk=pk)
        if product.like_users.filter(pk=request.user.pk).exists():
            product.like_users.remove(request.user)
        else:
            product.like_users.add(request.user)
        return redirect('products:index')
    return redirect('accounts:login')

products/templates/products/index.html
{% extends "base.html" %}

{% block content %}

<h1>Spart 마켓에 오신것을 환영합니다!</h1> 
<br>
{% if request.user.is_authenticated %}

        <a href="{% url 'products:product_creats' %}">
            <button class="btn btn-success">새로운 글 작성</button></a>
    
    {% else  %}
        <a href="{% url 'accounts:login' %}">
            <button class="btn btn-success">
            로그인하고 글 작성하기</button></a>
    
    {% endif %}

<div class="row row-cols-1 row-cols-md-3 g-4">
    


{% for product in products %}

<div class="col">
<div class="card" style="width: 20rem;">
    {% if product.image %}
    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.image }}">
    {% endif %}
    <div class="card-body">
      <a href="{% url 'products:product_detail' product.pk %}" class="card-title"><h4>{{ product.title }}</h4></a>
      <p class="card-text">{{ product.content }}</p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">작성자: {{product.author.username}}</li>
      <li class="list-group-item">가격: {{product.price}}원</li>
    </ul>
    <div class="card-bottom">

        <div class='card-like'>
            <form action="{% url 'products:like' product.pk %}" method="POST">
                {% csrf_token %}
            {% if request.user in product.like_users.all %}
                    <button class="btn btn-link text-danger">
                        <i class="bi bi-heart-fill"></i>
                    </button>
                    
                
            {% else %}
                <button class="btn btn-link text-danger" >
                    <i class="bi bi-heart"></i>
                </button>
            {% endif %}
    
            {{ product.like_users.all|length }}
            </form>
        </div>

        <div class='card-like'>
            조회수: {{ product.hits }}
        </div>
        
        <div class='card-like'>
            댓글수: {{ product.comment_count }}
        </div>
    </div>
  </div>
</div>
  {% endfor %}
    
  </div>
    
    

{% endblock content %}

products/templates/products/product_creats.html
{% extends 'base.html' %}

{% block content %}
    <h1>글 쓰기</h1><br>

    <form action='{% url 'products:product_creats' %}' method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><button type="submit">저장</button></p>
    </form>

    <a href="{% url 'products:index' %}">목록으로 돌아가기</a>

{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}


  <h2>글 상세 페이지</h2>
  <a href="{% url 'products:index' %}">목록으로 돌아가기</a>
  <h1>제목: {{ product.title }}</h1>
  <p>작성자: {{product.author.username}}</p>
  {% comment %} <form action="{% url "users:follow" user.pk %}" method="POST">
    {% csrf_token %}
        <button type="submit">팔로우</button>
  </form> {% endcomment %}
  <p>가격: {{product.price}}</p>

  {% if product.image %}
    <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.image }}">
  {% endif %}

  <p>내용: {{ product.content }}</p>
  <p>작성일시: {{ product.created_at }}</p>
  <p>수정일시: {{ product.updated_at }}</p>

  <a href="{% url 'products:index' %}">목록 보기</a>

  {% if user == product.author %} 
  <br>
  <a href="{% url 'products:product_update' product.pk %}">
    <button>수정하기</button>
  </a>
  <form action="{% url 'products:product_delete' product.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  {% endif %} 
  
  <br>
  <h2>댓글 {{ comments|length }} 개</h2>
  <br>
  <h2>좋아요 {{ product.like_users.all|length }} 개</h2>
  <br>
  {% for comment in comments  %}
  <ul>
    <li>
      {{ comment.content }} | {{ comment.created_at }}
      <p>작성자: {{ comment.user.username }}</p>

      {% if user == comment.user %} 
      {% comment %} 로그인한 사람과 글 쓴 사람이 같을시만 삭제버튼 보이게 {% endcomment %}
      <form action="{% url 'products:comment_delete' product.pk comment.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="댓글삭제">
      </form>
      {% endif %} 
    </li>
  </ul>

  {% empty %}
    <p>댓글이 없습니다.</p>

  {% endfor %}

  
  <br>
  <hr>
<h3>댓글</h3>
  {% if request.user.is_authenticated %}
  <form action="{% url "products:comment_create" product.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <input type="submit" value="댓글작성">
  </form>
  {% endif %}
  

{% endblock %}

products/templates/products/product_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit product</h1><br>

    <form action='{% url 'products:product_update' product.pk %}' method='POST'>
        {% csrf_token %}
        {{ form.as_p}}

        <p><button type="submit">수정</button></p>
    </form>

    <a href="{% url 'products:product_detail' product.pk %}">이전으로</a>

{% endblock content %}